### ISSUE TITLE
write acceptance criteria

### ISSUE THREAD

**Issue by Senopiece** [InnoSWP/cvparser_b21_01#39]

**Comment by NikitaGrigorenko** [comment]
User Story: As a user I want to see parse result once at a time, so I can switch between uploads
Scenario: Result of parsing multiple CVs
Given: Multiple CVs
When: Multiple CVs uploaded simultaneously
Then: Open one of them 

User Story: As a user I want to search for CVs with particular keywords for fast filtering
Scenario: User want to filter CVs based on keyword
Given: Keyword and multiple CVs
When: User enters keyword in search widget
Then: Filter CVs using this keyword

User Story: As a user I want the ability to remove files from uploaded files for easy user experience
Scenario: User want to delete CVs
Given: CV that need to be deleted
When: User selects 
Then: Delete selected CVs

User Story: As a user I want to download multiple JSON parse results so I can save time
Scenario: User want to extract CVs as a JSON
Given: CV that need to be extracted
When: User click button Extract 
Then: download file in JSON format

User Story: As a user I want to get fast access to the application on any platform so I can save time
Scenario: User want to get fast access
Given: Our platform
When: When user open our website
Then: Adaptive design and fast parsing
